services:
  ostinato-radio:
    build: .
    container_name: ostinato-radio
    ports:
      - "8087:8087"
    volumes:
      - ./config.toml:/app/config.toml:ro
    env_file:
      - .env
    restart: unless-stopped
    network_mode: host
